# Generated by Django 3.1.1 on 2020-09-28 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emptime',
            name='ename',
        ),
        migrations.RemoveField(
            model_name='leavedetail',
            name='ename',
        ),
        migrations.AlterField(
            model_name='emptime',
            name='eid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavedetail',
            name='eid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
